show_home:
  controller: Website\Controller\HomeController:showHomeAction
  secure: false
show_login:
  controller: Website\Controller\HomeController:ShowloginAction
  secure: false
show_addUser:
  controller: Website\Controller\HomeController:ShowAddUserAction
  secure: false
show_contact:
  controller: Website\Controller\HomeController:ShowContactAction
  secure: false
show_profilUser:
  controller: Website\Controller\HomeController:ShowProfilAction
  secure: true

user_login:
  controller: Website\Controller\UserController:logUserAction
  secure: false
user_add:
  controller: Website\Controller\UserController:addUserAction
  secure: false
user_logout:
  controller: Website\Controller\UserController:logOutAction
  secure: true
user_enable:
  controller: Website\Controller\UserController:enableUserAction
  secure: false