show_home:
  controller: Website\Controller\HomeController:showHomeAction
  secure: false
show_contact:
  controller: Website\Controller\HomeController:ShowContactAction
  secure: false


show_user:
  controller: Website\Controller\UserController:listUsersAction
  secure: false
show_users:
  controller: Website\Controller\UserController:showUserAction
  secure: false
user_login:
  controller: Website\Controller\UserController:logUserAction
  secure: false
user_add:
  controller: Website\Controller\UserController:addUserAction
  secure: false
user_logout:
  controller: Website\Controller\UserController:logOutAction
  secure: false
user_enable:
  controller: Website\Controller\UserController:enableUserAction
  secure: false
show_profilUser:
  controller: Website\Controller\UserController:ShowProfilAction
  secure: true
user_logout:
  controller: Website\Controller\UserController:logOutAction
  secure: false
user_enable:
  controller: Website\Controller\UserController:enableUserAction
  secure: false


product_list:
  controller: WebSite\Controller\ProductController:listProductsAction
  secure: false
product_show:
  controller: WebSite\Controller\ProductController:showProductAction
  secure: false
product_add:
  controller: WebSite\Controller\ProductController:addProductAction
  secure: true
product_delete:
  controller: WebSite\Controller\ProductController:deleteProductAction
  secure: true
